name: oauth2-proxy
version: 0.9.2
apiVersion: v1
appVersion: 3.1.0
home: https://github.com/pusher/oauth2_proxy
description: A reverse proxy that provides authentication with Google, Github or other providers
keywords:
- kubernetes
- oauth
- oauth2
- authentication
- google
- github
maintainers:
  - name: miouge1
    email: maxime@root314.com
sources:
- https://github.com/pusher/oauth2_proxy
engine: gotpl
