{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-snmp-exporter.name" . }}
    chart: {{ template "prometheus-snmp-exporter.chart" .  }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ template "prometheus-snmp-exporter.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "prometheus-snmp-exporter.fullname" . }}
{{- end }}
