kind: Service
apiVersion: v1
metadata:
  name: {{ template "prometheus-snmp-exporter.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    chart: {{ template "prometheus-snmp-exporter.chart" . }}
    app: {{ template "prometheus-snmp-exporter.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "prometheus-snmp-exporter.name" . }}
    release: "{{ .Release.Name }}"
